name: ci
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18.x
    steps:
      # CI setup
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # CI steps
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run ci:build
      - name: Lint
        run: npm run ci:lint
      - name: Test
        run: npm run ci:test

